project:
  type: website
  output-dir: docs
  resources:
    - "images"

execute:
  freeze: false

website:
  title: "Sergio J치cobo-Zavaleta"
  site-url: https://sergiojacobo.com
  description: Personal website and blog
  repo-url: https://github.com/SJacoboZavaleta/sergiojacobo
  #repo-actions: issue
  page-navigation: true
  back-to-top-navigation: true
  image: images/Logo_ThirdFoundation_es_card.png	
  navbar:
    title: "<span class='icon-line2'></span>Sergio<span class='icon-line3'></span><span class='icon-line'></span>Jacobo"
    right:
      - text: about
        href: about.qmd
      - text: research
        href: research.qmd
      - text: "blog: LTF"
        href: blog/index.qmd
      - text: talks
        href: talks.qmd
      - text: ideas
        href: ideas/ideas.qmd
      - text: contact
        href: contact.qmd
  favicon: images/favicon_ThirdFoundation.png
  twitter-card: 
    description: The personal website of Sergio J치cobo Zavaleta
    image: images/website_logo.png
    image-alt: |
      The Third Foundation's logo.
    image-width: 1100
    image-height: 600
    card-style: summary # alternative summary_large_image
    creator: "@JacoboZavaleta"
    site: "@JacoboZavaleta"
  open-graph: 
    description: The personal website of Sergio J치cobo Zavaleta
    image: images/website_logo.png
    image-alt: |
      The Third Foundation's logo.
    image-width: 1100
    image-height: 600
    locale: en-GB
  google-analytics:
    tracking-id: "G"
    anonymize-ip: true
  page-footer:
    left: |
      Copyright &copy; 2024 Sergio J치cobo Zavaleta|<br>
      Sitio web creado usando [![](/images/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org).
    center:
      - href: https://www.github.com/SJacoboZavaleta
        icon: github
        aria-label: GitHub
    right: |
      Inspirado por [Real World Data Science](https://realworlddatascience.net/) <br> y [EllaKaye](https://ellakaye.co.uk/)

format:
  html:
    theme: 
      light: assets/ek-theme-light.scss
      dark: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/ek-light.theme
      dark: assets/ek-dark.theme
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source