project:
  type: website
  output-dir: docs
  resources:
    - "images"
    
execute:
  freeze: auto

website:
  title: "Sergio Jacobo"
  site-url: https://sergiojacobo.com
  description: Personal website, portfolio and blog
  repo-url: https://github.com/SJacoboZavaleta/sergiojacobo
  #repo-actions: issue
  image: images/website_logo.png	
  navbar:
    #logo: ELLAKAYE-logo-light.png
    title: "<span class='icon-line2'></span>Sergio<span class='icon-line3'></span><span class='icon-line'></span>Jacobo"
    right:
      - text: about
        href: about.qmd
      - text: blog
        href: posts/posts.qmd
      - text: talks
        href: talks.qmd
      - text: ideas
        href: ideas/ideas.qmd
      - text: community
        href: community.qmd
      - text: contact
        href: contact.qmd
  favicon: images/ThirdFoundation_favicon.png
  twitter-card: 
    title: Sergio Jacobo
    description: The personal website of Sergio Jacobo
    image: images/website_logo.png
    image-alt: |
      A square logo made from Sergio Jacobo's name and The Third Foundation's logo.
    image-width: 500
    image-height: 500
    card-style: summary # alternative summary_large_image
    creator: "@JacoboZavaleta"
    site: "@JacoboZavaleta"
  open-graph: 
    description: The personal website of Sergio Jacobo
    image: images/website_logo.png
    image-alt: |
      A square logo made from Sergio Jacobo's name and The Third Foundation's logo.
    image-width: 500
    image-height: 500
    locale: en-GB
  google-analytics:
    tracking-id: "G"
    anonymize-ip: true
  page-footer:
    left: |
      Copyright &copy; 2024 Sergio Jácobo |<br>
      Este sitio web fue creado usando [![](/images/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org).
    center:
      - href: https://www.github.com/SJacoboZavaleta
        icon: github
        aria-label: GitHub
    right: |
      Inspirado por [Real World Data Science](https://realworlddatascience.net/) <br> y [EllaKaye](https://ellakaye.co.uk/)

format:
  html:
    theme: 
      light: assets/ek-theme-light.scss
      dark: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/ek-light.theme
      dark: assets/ek-dark.theme
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source